<testsuite name="test_scenarios.login.User is able to login to OrangeHRM application using correct credentials" tests="3" errors="1" failures="1" skipped="0" time="7.49103" timestamp="2023-01-06T10:12:53.752602" hostname="Reanolds-MacBook-Air.local"><testcase classname="test_scenarios.login.User is able to login to OrangeHRM application using correct credentials" name="Navigate to the application -- @1.1 " status="passed" time="1.400496"><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Navigate to the application -- @1.1 
    Given I navigate to "https://opensource-demo.orangehrmlive.com/index.php" ... passed in 1.397s
    Then I see proper "OrangeHRM" ... passed in 0.003s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
Page title is OrangeHRM

]]>
</system-out></testcase><testcase classname="test_scenarios.login.User is able to login to OrangeHRM application using correct credentials" name="Navigate to the application -- @1.2 " status="failed" time="1.548965"><failure type="AssertionError" message="">
<![CDATA[
Failing step: Then I see proper "Hello, World" ... failed in 0.003s
Location: features/test_scenarios/login.feature:8
Traceback (most recent call last):
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/login_steps.py", line 18, in verify_page_title
    assert page_title == context.browser.get_page_title()
AssertionError

Captured stdout:
Page title is OrangeHRM]]>
</failure><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Navigate to the application -- @1.2 
    Given I navigate to "https://opensource-demo.orangehrmlive.com/index.php" ... passed in 1.546s
    Then I see proper "Hello, World" ... failed in 0.003s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
Page title is OrangeHRM

]]>
</system-out></testcase><testcase classname="test_scenarios.login.User is able to login to OrangeHRM application using correct credentials" name="Login to application -- @1.1 " status="failed" time="4.541568"><error type="NoSuchWindowException" message="Message: no such window: target window already closed&#10;from unknown error: web view not found&#10;  (Session info: chrome=108.0.5359.124)&#10;Stacktrace:&#10;0   chromedriver                        0x000000010075bb7c chromedriver + 4209532&#10;1   chromedriver                        0x00000001006e7418 chromedriver + 3732504&#10;2   chromedriver                        0x000000010039a368 chromedriver + 271208&#10;3   chromedriver                        0x00000001003756fc chromedriver + 120572&#10;4   chromedriver                        0x00000001003fa660 chromedriver + 665184&#10;5   chromedriver                        0x000000010040cfbc chromedriver + 741308&#10;6   chromedriver                        0x00000001003c859c chromedriver + 460188&#10;7   chromedriver                        0x00000001003c9644 chromedriver + 464452&#10;8   chromedriver                        0x000000010072d30c chromedriver + 4018956&#10;9   chromedriver                        0x0000000100730fd8 chromedriver + 4034520&#10;10  chromedriver                        0x000000010073711c chromedriver + 4059420&#10;11  chromedriver                        0x0000000100731bac chromedriver + 4037548&#10;12  chromedriver                        0x000000010070bbb0 chromedriver + 3881904&#10;13  chromedriver                        0x000000010074e120 chromedriver + 4153632&#10;14  chromedriver                        0x000000010074e274 chromedriver + 4153972&#10;15  chromedriver                        0x000000010076282c chromedriver + 4237356&#10;16  libsystem_pthread.dylib             0x000000019c9d906c _pthread_start + 148&#10;17  libsystem_pthread.dylib             0x000000019c9d3e2c thread_start + 8&#10;">
<![CDATA[
Failing step: When I enter username "Admin" ... failed in 3.073s
Location: features/test_scenarios/login.feature:16
Traceback (most recent call last):
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/login_steps.py", line 23, in enter_login
    context.browser.input_text(LoginPageSelectors.LOGIN_FIELD, username)
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/engine/custom_test_driver/browser.py", line 44, in input_text
    WebDriverWait(self.driver, self.timeout).until(EC.visibility_of_element_located(by_locator)).send_keys(text)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 78, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Users/reanoldpiatrenka/SoftwareDevelopment/PycharmProjects/openHRMautomationProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=108.0.5359.124)
Stacktrace:
0   chromedriver                        0x000000010075bb7c chromedriver + 4209532
1   chromedriver                        0x00000001006e7418 chromedriver + 3732504
2   chromedriver                        0x000000010039a368 chromedriver + 271208
3   chromedriver                        0x00000001003756fc chromedriver + 120572
4   chromedriver                        0x00000001003fa660 chromedriver + 665184
5   chromedriver                        0x000000010040cfbc chromedriver + 741308
6   chromedriver                        0x00000001003c859c chromedriver + 460188
7   chromedriver                        0x00000001003c9644 chromedriver + 464452
8   chromedriver                        0x000000010072d30c chromedriver + 4018956
9   chromedriver                        0x0000000100730fd8 chromedriver + 4034520
10  chromedriver                        0x000000010073711c chromedriver + 4059420
11  chromedriver                        0x0000000100731bac chromedriver + 4037548
12  chromedriver                        0x000000010070bbb0 chromedriver + 3881904
13  chromedriver                        0x000000010074e120 chromedriver + 4153632
14  chromedriver                        0x000000010074e274 chromedriver + 4153972
15  chromedriver                        0x000000010076282c chromedriver + 4237356
16  libsystem_pthread.dylib             0x000000019c9d906c _pthread_start + 148
17  libsystem_pthread.dylib             0x000000019c9d3e2c thread_start + 8

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Login to application -- @1.1 
    Given I navigate to "https://opensource-demo.orangehrmlive.com/index.php" ... passed in 1.468s
    When I enter username "Admin" ... failed in 3.073s
    And I enter password "admin123" ... skipped in 0.000s
    And I click on login button ... skipped in 0.000s
    Then I see dashboard ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>